### PR TITLE
fix: no newline cmake error

### PR DESCRIPTION
**Pull request by SYaoJun**
when I run the command: cmake --build . 
return the error below
so I fix it 
plog

### CODE REVIEW

**Comment by SergiusTheBest** [comment]
Thank you! By the way, what compiler do you use?

**Comment by SYaoJun** [comment]
Maybe clang
QQ20230813-085607@2x

**Comment by SYaoJun** [comment]
Is this modification feasible？

**Comment by SergiusTheBest** [comment]
Absolutely! Thank you!

**Pull request merged**
