### PR TITLE
 make plog able to be exported from Windows dll,  Fix millisecond showing by TxtFormatter

### PR DESCRIPTION
**Pull request by foreverr**
1. By adding a definition COMMON_EXPORTS under a Visual studio project, plog can be able to use the same instance between dll & exe

2. millisecond is showing incorrectly, add cast from unsigned short to int to fix it.

### CODE REVIEW

**Comment by SergiusTheBest** [comment]
Hi!

Could you post the incorrect milliseconds formatting? I'm not sure how casting from `unsigned short` to `int` fixes anything.

**Comment by foreverr** [comment]
Without casting to int, log looks like following:

2018-05-22 20:07:43.00ɒ DEBUG [32160] [logger::init@139] ppp
2018-05-22 20:11:03.00Ũ DEBUG [580] [logger::init@139] ppp
2018-05-22 20:12:12.00l DEBUG [37260] [logger::init@139] ppp
2018-05-22 23:09:39.00̌ DEBUG [40296] [main@57] A message from the main application!
2018-05-22 23:11:12.00ƪ DEBUG [53504] [commonLogger::init@139] ppp
2018-05-22 23:11:16.00̰ DEBUG [53504] [main@57] A message from the main application!

You can see that all milliseconds printed incorrectly. cast it into int won't hurt anything and can fix this problem.
BTW I use plog under Windows. Thank you for you great work!

**Comment by foreverr** [comment]
Hi, I fixed the building problem. Could you check my patches again? Thank you so much.
Now by adding a definition PLOG_EXPORTS under a Visual studio 'Library' project, and adding PLOG_IMPORTS under 'Application(.exe)' project, plog can use the same instance between dll & exe.
For Standalone application, you don't need to change anything just like your original usage.

**Comment by wjx0912** [comment]
it's seems the patch not merge, the latest code still not log in 2 modules(exe normal, and dll not write to log file).

**Comment by SergiusTheBest** [comment]
@wjx0912 Thank you for reminding me, just forgot about this.

**Pull request merged**
