### PR TITLE
Logging std::filesystem::path without having to convert to a std::string

### PR DESCRIPTION
**Pull request by dannypike**
I find myself adding support for directly logging ```path``` values to all my projects. I'm not sure if you've considered adding this and decided not to for some reason but, just in case you hadn't thought about it, here's a PR that works for me with Visual Studio.

I'm not familiar with the status of ```std::filesystem``` in other compilers, I'm afraid.

### CODE REVIEW

**Comment by SergiusTheBest** [comment]
Thank you! I'll take a look at it.

**Comment by dannypike** [comment]
It says that the build is failing. I only have Visual Studio 16 here (2019), so I can't check what happens with VS 2015

**Comment by SergiusTheBest** [comment]
Oh, don't worry about that.

**Comment by SergiusTheBest** [comment]
I fixed it by using some metaprogramming, so there is no need to include <filesystem> or check C++ version.

**Pull request closed without merging**
