### PR TITLE
Added share.h for compilation with mingw & colored TXT Formatter

### PR DESCRIPTION
**Pull request by bastianseeleib**
Without the inclusion of share.h _SH_DENYWR is undefined when compiling with mingw.

### CODE REVIEW

**Comment by SergiusTheBest** [comment]
This is for [Mingw-w64](http://mingw-w64.org/), right?

**Comment by bastianseeleib** [comment]
Yes, Mingw-w64.

**Comment by bastianseeleib** [comment]
bildschirmfoto 2015-09-17 um 19 01 46

**Comment by SergiusTheBest** [comment]
Unfortunately windows doesn't support ANSI escape sequences. So I had to move coloring from the formatter to an appender. Now the whole line is colored.
color-console-appender

**Pull request closed without merging**
