### PR TITLE
Check for existing windows event log

### PR DESCRIPTION
**Pull request by ThirtySomething**
fix: cast from size_t to DWORD
new: check for existing windows event log

### CODE REVIEW

**Comment by ThirtySomething** [comment]
This is required in the case of a program without an installer. By the way - how to call the methods of (un-)registering an eventlog from a [NSIS ](http://nsis.sourceforge.net/Main_Page)based installer?

**Comment by SergiusTheBest** [comment]
Hi there,

I am not sure why one should care whether the event log already registered? Could you explain it a little bit more?

About NSIS: I see 2 ways there:
1) Use native NSIS registry functions (`WriteRegStr` and so on).
2) Make install/unsinstall functions callable from the outer world: add command line parameters to your EXE or export functions from your DLL. Then call it form NSIS.

**Comment by ThirtySomething** [comment]
If the creation of the event log fails, no one will be noticed. The add method does not return any state about success. If you rely on the event log and it's not created, you're screwed up. With this method you can check from any part (either installer or your application) the existence of the event log and drop the user a note in case it's missing.

Thanks about your proposals about NSIS. Helped me to order my mind and offers me additional solutions.

**Comment by SergiusTheBest** [comment]
I merged to the master and added some fixes.

**Pull request merged**
